// TEPS 청해 Part 1-2 스타일 구어체 + 관용 표현 학습 문장
export interface LoadingPhrase {
  en: string
  ko: string
}

export const LOADING_PHRASES: LoadingPhrase[] = [
  { en: "Could you do me a favor?", ko: "부탁 하나 해도 될까요?" },
  { en: "I'm tied up at the moment.", ko: "지금 좀 바빠요." },
  { en: "Let's call it a day.", ko: "오늘은 이만 끝내죠." },
  { en: "That rings a bell.", ko: "어디서 들어본 것 같아요." },
  { en: "I'll look into it right away.", ko: "바로 알아볼게요." },
  { en: "It slipped my mind.", ko: "깜빡 잊었어요." },
  { en: "You can say that again.", ko: "정말 그 말이 맞아요." },
  { en: "I'm on the fence about it.", ko: "아직 결정을 못 했어요." },
  { en: "Don't jump to conclusions.", ko: "성급하게 결론짓지 마세요." },
  { en: "We're running out of time.", ko: "시간이 얼마 안 남았어요." },
  { en: "It's on the tip of my tongue.", ko: "입에서 맴도는데 기억이 안 나요." },
  { en: "I couldn't agree more.", ko: "전적으로 동감이에요." },
  { en: "Let me get back to you on that.", ko: "그건 나중에 다시 알려드릴게요." },
  { en: "I'll keep that in mind.", ko: "그거 기억해 둘게요." },
  { en: "It goes without saying.", ko: "두말할 필요 없죠." },
  { en: "I'm a bit under the weather.", ko: "몸이 좀 안 좋아요." },
  { en: "Could you fill me in?", ko: "상황 좀 알려줄래요?" },
  { en: "Let's get down to business.", ko: "본론으로 들어가죠." },
  { en: "I didn't catch that.", ko: "못 알아들었어요." },
  { en: "It's no big deal.", ko: "별거 아니에요." },
  { en: "I'm counting on you.", ko: "당신을 믿고 있어요." },
  { en: "That's easier said than done.", ko: "말이야 쉽죠." },
  { en: "I have mixed feelings about it.", ko: "기분이 복잡해요." },
  { en: "Bear with me for a moment.", ko: "잠깐만 기다려 주세요." },
  { en: "It's out of the question.", ko: "그건 절대 안 돼요." },
  { en: "I'll take a rain check.", ko: "다음에 할게요." },
  { en: "What brings you here?", ko: "여기 웬일이세요?" },
  { en: "I'm swamped with work.", ko: "일에 파묻혀 있어요." },
  { en: "Let's play it by ear.", ko: "상황 봐서 결정해요." },
  { en: "I can't make heads or tails of it.", ko: "전혀 이해가 안 돼요." },
  { en: "You hit the nail on the head.", ko: "정확히 맞았어요." },
  { en: "I'm all ears.", ko: "열심히 듣고 있어요." },
  { en: "That's beside the point.", ko: "그건 논점에서 벗어난 얘기예요." },
  { en: "I'll give it a shot.", ko: "한번 해볼게요." },
  { en: "Don't get me wrong.", ko: "오해하지 마세요." },
  { en: "It comes with the territory.", ko: "그건 어쩔 수 없는 거예요." },
  { en: "I'm at a loss for words.", ko: "뭐라고 말해야 할지 모르겠어요." },
  { en: "Let's wrap it up.", ko: "마무리하죠." },
  { en: "I'll sleep on it.", ko: "하루 자고 생각해 볼게요." },
  { en: "We're on the same page.", ko: "우리 의견이 같네요." },
  { en: "I was just about to say that.", ko: "저도 그 말 하려던 참이었어요." },
  { en: "The sooner, the better.", ko: "빠르면 빠를수록 좋아요." },
  { en: "It's a long shot, but let's try.", ko: "가능성은 낮지만 해보죠." },
  { en: "I'm in no rush.", ko: "급하지 않아요." },
  { en: "That's the last straw.", ko: "이제 참을 수가 없어요." },
  { en: "I have a lot on my plate.", ko: "할 일이 산더미예요." },
  { en: "It's not my cup of tea.", ko: "제 취향은 아니에요." },
  { en: "Let me think it over.", ko: "좀 더 생각해 볼게요." },
  { en: "You're barking up the wrong tree.", ko: "엉뚱한 데서 찾고 있는 거예요." },
  { en: "I'll keep my fingers crossed.", ko: "행운을 빌게요." },
  { en: "Hold on a second.", ko: "잠깐만요." },
  { en: "It's worth a try.", ko: "시도해 볼 가치가 있어요." },
  { en: "I'm looking forward to it.", ko: "기대하고 있어요." },
  { en: "Can I pick your brain?", ko: "좀 물어봐도 될까요?" },
  { en: "That makes two of us.", ko: "저도 마찬가지예요." },
  { en: "I owe you one.", ko: "신세 졌어요." },
  { en: "Cut to the chase.", ko: "핵심만 말해 주세요." },
  { en: "I'll take your word for it.", ko: "당신 말 믿을게요." },
  { en: "Let's not beat around the bush.", ko: "돌려 말하지 맙시다." },
  { en: "I'm having second thoughts.", ko: "다시 생각해 보고 있어요." },
  { en: "Don't push your luck.", ko: "너무 욕심부리지 마세요." },
  { en: "Something came up.", ko: "갑자기 일이 생겼어요." },
  { en: "I'll make it up to you.", ko: "나중에 보답할게요." },
  { en: "That went over my head.", ko: "무슨 말인지 이해를 못 했어요." },
  { en: "I can't help it.", ko: "어쩔 수 없어요." },
  { en: "Let's see how it goes.", ko: "어떻게 되는지 지켜보죠." },
  { en: "I've been meaning to ask you.", ko: "진작 물어보려고 했어요." },
  { en: "It dawned on me.", ko: "문득 깨달았어요." },
  { en: "Take it or leave it.", ko: "하든지 말든지예요." },
  { en: "I can relate to that.", ko: "충분히 공감해요." },
  { en: "You're pulling my leg.", ko: "농담하시는 거죠?" },
  { en: "I'll get right on it.", ko: "바로 처리할게요." },
  { en: "It's a stone's throw from here.", ko: "여기서 아주 가까워요." },
  { en: "I'm keeping my options open.", ko: "여러 가능성을 열어두고 있어요." },
  { en: "You've got a point there.", ko: "일리가 있네요." },
  { en: "I'll cross that bridge when I come to it.", ko: "그때 가서 생각할게요." },
  { en: "It's music to my ears.", ko: "듣기 좋은 소리네요." },
  { en: "I'm in over my head.", ko: "감당이 안 돼요." },
  { en: "Don't hold your breath.", ko: "너무 기대하지 마세요." },
  { en: "I have no clue.", ko: "전혀 모르겠어요." },
  { en: "It's now or never.", ko: "지금 아니면 기회가 없어요." },
  { en: "I'm not in the mood.", ko: "그럴 기분이 아니에요." },
  { en: "Let me put it this way.", ko: "이렇게 말씀드릴게요." },
  { en: "I'm glad you brought that up.", ko: "그 얘기 꺼내주셔서 다행이에요." },
  { en: "We'll figure something out.", ko: "방법을 찾을 거예요." },
  { en: "That's out of my hands.", ko: "그건 제 소관이 아니에요." },
  { en: "I've heard so much about you.", ko: "이야기 많이 들었어요." },
  { en: "Can we reschedule?", ko: "일정을 바꿀 수 있을까요?" },
  { en: "I wouldn't count on it.", ko: "그건 기대하지 않는 게 좋을 거예요." },
  { en: "Let's split the bill.", ko: "각자 내죠." },
  { en: "I'm running a bit late.", ko: "좀 늦을 것 같아요." },
  { en: "That doesn't add up.", ko: "앞뒤가 안 맞네요." },
  { en: "Give me a ballpark figure.", ko: "대략적인 수치를 알려주세요." },
  { en: "I'm not buying it.", ko: "그 말은 안 믿어요." },
  { en: "We need to touch base later.", ko: "나중에 연락하죠." },
  { en: "I'm drawing a blank.", ko: "아무것도 떠오르지 않아요." },
  { en: "It's a no-brainer.", ko: "생각할 것도 없이 당연하죠." },
  { en: "I'll pass on that.", ko: "그건 사양할게요." },
  { en: "You're in good hands.", ko: "잘 맡기신 거예요." },
  { en: "I need to blow off some steam.", ko: "스트레스 좀 풀어야겠어요." },
]

export function getRandomPhrase(): LoadingPhrase {
  return LOADING_PHRASES[Math.floor(Math.random() * LOADING_PHRASES.length)]
}
